    package itson.sistemarestaurantepresentacion.comandas;

import itson.sistemarestaurantenegocio.IComandasBO;

/**
 *
 * @author Pedro Morales Esquer, Juan Pablo Heras Carrazco, Victoria Valenzuela Soto
 */
public class AgregarDetalleComanda extends javax.swing.JFrame {

    private IComandasBO comandasBO;
    /**
     * Creates new form Productos
     */
    public AgregarDetalleComanda(IComandasBO comandasBO) {
        initComponents();
        this.setTitle("Comandas");
        this.setResizable(false);
        this.setSize(400,250);
        this.setLocationRelativeTo(null);
        this.comandasBO = comandasBO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        lblStockActual = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblStockActual1 = new javax.swing.JLabel();
        lblStockActual2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setBackground(new java.awt.Color(221, 218, 174));
        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGeneral.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 184, 52));

        lblStockActual.setBackground(new java.awt.Color(0, 0, 0));
        lblStockActual.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        lblStockActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockActual.setText("Producto");
        panelGeneral.add(lblStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, -1));

        jButton1.setText("Cancelar");
        panelGeneral.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 78, -1));

        jButton2.setText("Aceptar");
        panelGeneral.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 188, 150, 40));

        lblStockActual1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblStockActual1.setText("Comentario:");
        panelGeneral.add(lblStockActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, -1));

        lblStockActual2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblStockActual2.setText("Cantidad:");
        panelGeneral.add(lblStockActual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));
        panelGeneral.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 73, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblStockActual;
    private javax.swing.JLabel lblStockActual1;
    private javax.swing.JLabel lblStockActual2;
    private javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
